baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "relearn"

[params]
  themeVariant = ["green","blue","neon"]

[[menu.shortcuts]]
  name = "Github Account"
  url = "https://github.com/jwoolbright23"
  weight = 99998

